### ISSUE TITLE
EXP Type Mismatch

### ISSUE THREAD

**Issue by AXAz0r** [lu-ci/apex-sigma-core#115]
Trace Class:
```
<built-in method with_traceback of AttributeError object at 0x7f5555077fc0>
```
Trace Details:
```py
Traceback (most recent call last):
  File "/srv/apex-sigma/sigma/core/mechanics/command.py", line 272, in execute
    await self.add_usage_exp(message)
  File "/srv/apex-sigma/sigma/core/mechanics/command.py", line 189, in add_usage_exp
    await self.db.add_experience(message.author, message.guild, award_xp)
  File "/srv/apex-sigma/sigma/core/mechanics/database.py", line 106, in add_experience
    total_xp = entry.get('total') or 0
AttributeError: 'NoneType' object has no attribute 'get' 
```

**Comment by AXAz0r** [comment]
Fixed in `13240778f8744b1c72b99cebe51fa3bb1976795a`.
